name: el-plus-admin

x-common-build-args: &common-build-args
  NPMRC_REGISTRY: ${NPMRC_REGISTRY:-https://registry.npmjs.org}

x-common-build-options: &common-build-options
  args:
    <<: *common-build-args

x-common-environments: &common-environments
  FILES_DIR_PATH: /files
  MAIL_SERVER_HOST: ${MAIL_SERVER_HOST}
  MAIL_SERVER_PORT: ${MAIL_SERVER_PORT}
  MONGODB_URI: ${MONGODB_URI}
  NODE_ENV: production
  NODEMAILER_USE_SECURE: ${NODEMAILER_USE_SECURE}
  REDIS_URI: ${REDIS_URI}

services:
  # Backend
  backend:
    build:
      args:
        <<: *common-build-args
        SESSION_SECRET_KEY: ${BACKEND_SESSION_SECRET_KEY}
        SESSION_SECRET_KEY_ENCODING: ${BACKEND_SESSION_SECRET_KEY_ENCODING}
      context: ./backend
    container_name: el-plus-admin-backend
    environment:
      <<: *common-environments
      NITRO_CLUSTER_WORKERS: ${BACKEND_WORKERS}
      SEND_MAIL_FROM: ${BACKEND_SEND_MAIL_FROM}
      SEND_MAIL_TO: ${BACKEND_SEND_MAIL_TO}
    restart: always
    volumes:
      - ${FILES_DIR_PATH}:/files

  # Frontend
  frontend:
    build:
      <<: *common-build-options
      context: ./frontend
    container_name: el-plus-admin-frontend
    environment:
      <<: *common-environments
    volumes:
      - frontend-dist:/frontend-dist

  # Nginx
  nginx:
    build:
      context: ./nginx
    container_name: el-plus-admin-nginx
    depends_on:
      - backend
      - frontend
    ports:
      - 127.0.0.1:${NGINX_EXPOSE_PORT}:80
    restart: always
    volumes:
      - read_only: true
        source: ${FILES_DIR_PATH}
        target: /files
        type: bind
      - read_only: true
        source: frontend-dist
        target: /frontend-dist
        type: volume

volumes:
  frontend-dist:
