name: kiki-core-stack

x-common-build-args: &common-build-args
  NPM_REGISTRY: ${NPM_REGISTRY:-https://registry.npmjs.org}

x-common-build-options: &common-build-options
  args:
    <<: *common-build-args

x-common-environments: &common-environments
  FILES_DIR_PATH: /files
  MAIL_SERVER_HOST: ${MAIL_SERVER_HOST}
  MAIL_SERVER_PORT: ${MAIL_SERVER_PORT}
  MONGODB_URI: ${MONGODB_URI}
  NODE_ENV: production
  NODEMAILER_USE_SECURE: ${NODEMAILER_USE_SECURE}
  REDIS_URI: ${REDIS_URI}

services:
  # Admin backend
  admin-backend:
    build:
      args:
        <<: *common-build-args
        SESSION_SECRET_KEY: ${ADMIN_BACKEND_SESSION_SECRET_KEY}
        SESSION_SECRET_KEY_ENCODING: ${ADMIN_BACKEND_SESSION_SECRET_KEY_ENCODING}
      context: ./admin-backend
    container_name: kiki-core-stack-admin-backend
    environment:
      <<: *common-environments
      NITRO_CLUSTER_WORKERS: ${ADMIN_BACKEND_WORKERS}
      SEND_MAIL_FROM: ${ADMIN_BACKEND_SEND_MAIL_FROM}
      SEND_MAIL_TO: ${ADMIN_BACKEND_SEND_MAIL_TO}
    restart: always
    volumes:
      - ${FILES_DIR_PATH}:/files

  # Admin frontend
  admin-frontend:
    build:
      <<: *common-build-options
      context: ./admin-frontend
    container_name: kiki-core-stack-admin-frontend
    environment:
      <<: *common-environments
    volumes:
      - admin-frontend-dist:/admin-frontend-dist

  # Nginx
  nginx:
    build:
      context: ./nginx
    container_name: kiki-core-stack-nginx
    depends_on:
      - admin-backend
      - admin-frontend
    ports:
      - 127.0.0.1:${ADMIN_WEB_NGINX_EXPOSE_PORT}:80
    restart: always
    volumes:
      - read_only: true
        source: ${FILES_DIR_PATH}
        target: /files
        type: bind
      - read_only: true
        source: admin-frontend-dist
        target: /admin-frontend-dist
        type: volume

volumes:
  admin-frontend-dist:
