name: '${PROJECT_NAME}'

networks:
  default:
    driver: bridge
  infra_services:
    external: true
    name: '${PROJECT_NAME}-infra-services_default'

secrets:
  MONGODB_URI:
    environment: MONGODB_URI
  REDIS_URL:
    environment: REDIS_URL

include:
  - stacks/admin-frontend.compose.yaml
  - stacks/management-backend.compose.yaml
  - stacks/ops-workers-ts.compose.yaml
