services:
  management-backend:
    extends:
      file: ../common.compose.yaml
      service: common-service
    build:
      context: ../repos/management-backend
    container_name: '${PROJECT_NAME}-management-backend'
    image: '${DOCKER_REGISTRY_HOST:+${DOCKER_REGISTRY_HOST}/}${PROJECT_NAME}/management-backend'
    ports:
      - '127.0.0.1:${MANAGEMENT_BACKEND_EXPOSE_PORT:?must be set}:8000'
    secrets:
      - MONGODB_URI
      - REDIS_URL
